language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - python setup.py -q install
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage==3.7.1
  - pip install coveralls
script:
  - coverage run --source=loadimpactcli setup.py test
after_success:
  - coveralls
